DO $$
    BEGIN
        RAISE NOTICE 'INICIANDO EXECUCAO DO SCRIPT INIT-POSTGRES.SQL';
    END $$;

CREATE SCHEMA IF NOT EXISTS cadastro AUTHORIZATION cadastro;
GRANT CONNECT ON DATABASE cadastro_avd_2025 TO cadastro;

CREATE SCHEMA IF NOT EXISTS cadastro AUTHORIZATION cadastro;
GRANT CONNECT ON DATABASE cadastro_avd_2025 TO cadastro;

GRANT USAGE, CREATE ON SCHEMA cadastro TO cadastro;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cadastro TO cadastro;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA cadastro TO cadastro;

ALTER DEFAULT PRIVILEGES IN SCHEMA cadastro
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cadastro;

ALTER DEFAULT PRIVILEGES IN SCHEMA cadastro
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cadastro;
ALTER USER cadastro SET search_path TO cadastro;

DO $$
    BEGIN
        RAISE NOTICE 'FINALIZANDO EXECUCAO DO SCRIPT INIT-POSTGRES.SQL';
    END $$;
